version: '3.9'

services:
  vacationservice:
    build:
      context: .
      dockerfile: VacationService/VacationService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: vacationservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
    ports:
      - 5000:80
    depends_on:
      - eventbus
      - logger

  flightservice:
    build:
      context: .
      dockerfile: FlightService/FlightService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: flightservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - ravendb
      
  hotelservice:
    build:
      context: .
      dockerfile: HotelService/HotelService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: hotelservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - ravendb
      
  carservice:
    build:
      context: .
      dockerfile: CarService/CarService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: carservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - ravendb
      
  trackingservice:
    build:
      context: .
      dockerfile: TrackingService/TrackingService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: trackingservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - ravendb
      
  ticketservice:
    build:
      context: .
      dockerfile: TicketService/TicketService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: ticketservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5005:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/minio.env
    depends_on:
      - eventbus
      - logger
      - blobstorage    
      
  gatewayservice:
    build:
      context: .
      dockerfile: GatewayService/GatewayService.Api/Dockerfile
      args:
        - GithubToken=${NUGET_API}
    container_name: gatewayservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5006:80
      - 5007:443
    env_file:
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/gateway.env
    depends_on:
      - logger

  logger:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    container_name: logger

  eventbus:
    image: masstransit/rabbitmq
    container_name: eventbus
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ./EventBus/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./EventBus/enabled_plugins:/etc/rabbitmq/enabled_plugins
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./Monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DEFAULT_INSTANCE_NAME=local
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_APP_MODE=development
    volumes:
      - ./Monitoring/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./Monitoring/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./Monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - prometheus
     
  blobstorage:
    image: minio/minio
    container_name: blobstorage
    ports:
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=access
      - MINIO_ROOT_PASSWORD=secret1234
    command: server /data --console-address ":9001"
      
  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    container_name: ravendb
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
