version: '3.9'

networks:
  service_net:

services:
  vacationservice:
    build:
      context: VacationService
      dockerfile: VacationService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    hostname: vacationservice
    container_name: vacationservice
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
    ports:
      - 5000:80
    depends_on:
      - eventbus
      - logger
    networks:
      - service_net

  flightservice:
    build:
      context: FlightService
      dockerfile: FlightService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: flightservice
    hostname: flightservice
    ports:
      - 5001:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/neo4j.env
      - ./EnvironmenFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - neo4j
    networks:
      - service_net
      
  hotelservice:
    build:
      context: HotelService
      dockerfile: HotelService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: hotelservice
    hostname: hotelservice
    ports:
      - 5002:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/neo4j.env
      - ./EnvironmenFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - neo4j
    networks:
      - service_net
      
  carservice:
    build:
      context: CarService
      dockerfile: CarService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: carservice
    hostname: carservice
    ports:
      - 5003:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/neo4j.env
      - ./EnvironmenFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
      - neo4j
    networks:
      - service_net
      
  trackingservice:
    build:
      context: TrackingService
      dockerfile: TrackingService.Worker/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: trackingservice
    hostname: trackingservice
    ports:
      - 5004:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/neo4j.env
      - ./EnvironmentFiles/prometheus.env
      - ./EnvironmenFiles/ravendb.env
    depends_on:
      - eventbus
      - logger
    networks:
      - service_net
      
  gatewayservice:
    build:
      context: GatewayService
      dockerfile: GatewayService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: gatewayservice
    hostname: gatewayservice
    ports:
      - 5005:80
      - 5006:443
    env_file:
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/gateway.env
    depends_on:
      - logger
    networks:
      - service_net
      
  ticketservice:
    build:
      context: TicketService
      dockerfile: TicketService.Api/Dockerfile
      args:
        - Configuration=${Configuration}
        - Environment=${Environment}
        - GithubToken=${NUGET_API}
    container_name: ticketservice
    hostname: ticketservice
    ports:
      - 5007:80
    env_file:
      - ./EnvironmentFiles/eventbus.env
      - ./EnvironmentFiles/logging.env
      - ./EnvironmentFiles/neo4j.env
      - ./EnvironmentFiles/minio.env
    depends_on:
      - eventbus
      - logger
      - neo4j
      - blobstorage
    networks:
      - service_net  

  logger:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    container_name: logger
    hostname: logger
    networks:
      - service_net

  eventbus:
    image: masstransit/rabbitmq
    hostname: eventbus
    container_name: eventbus
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ./EventBus/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./EventBus/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - service_net
      
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    networks:
      - service_net
    volumes:
      - ./Neo4j/neo4j.conf:/conf  
      - ./Neo4j/initialize.cypher:/initialize.cypher
    ports:
      - "7474:7474"
      - "7687:7687"
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./Monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - service_net
          
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    volumes:
      - ./Monitoring/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./Monitoring/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./Monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - service_net
     
  blobstorage:
    image: minio/minio
    hostname: blobstorage
    container_name: blobstorage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=access
      - MINIO_ROOT_PASSWORD=secret1234
    command: minio server /data --console-address ":9001"  
    networks:
      - service_net
      
  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    hostname: ravendb
    container_name: ravendb
    ports:
      - 8080-8080
    environment:
      - RAVEN_Setup_Mode='None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
    networks:
      - service_net   
