apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackingservice-deployment
spec:
  selector:
    matchLabels:
      app: trackingservice
  replicas: 2    
  template:
    metadata:
      labels:
        app: trackingservice
    spec:
      containers:
      - name: trackingservice
        image: jokk-itu/trackingservice:master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: internal
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: Logging__SeqUri
            valueFrom:
              configMapKeyRef:
                name: logger-config
                key: url
          - name: EventBus__Hostname
            valueFrom:
              configMapKeyRef:
                name: eventbus-config
                key: url
          - name: EventBus__Port
            valueFrom:
              configMapKeyRef:
                name: eventbus-config
                key: port
          - name: EventBus__Username
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key: username
          - name: EventBus__Password
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key: password
          - name: RavenSettings__Urls__0
            valueFrom:
              configMapKeyRef:
                name: raven-config
                key: url  
---
apiVersion: v1
kind: Service
metadata:
  name: trackingservice-service
spec:
  type: NodePort
  selector:
    app: trackingservice
  ports:
  - port: 5004
    targetPort: internal
    nodePort: 30004
