apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacationservice-deployment
spec:
  selector:
    matchLabels:
      app: vacationservice
  replicas: 2    
  template:
    metadata:
      labels:
        app: vacationservice
    spec:
      containers:
      - name: vacationservice
        image: jokk-itu/vacationservice:master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: internal
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: Logging__SeqUri
            valueFrom:
              configMapKeyRef:
                name: logger-config
                key: url
          - name: EventBus__Hostname
            valueFrom:
              configMapKeyRef:
                name: eventbus-config
                key: url
          - name: EventBus__Port
            valueFrom:
              configMapKeyRef:
                name: eventbus-config
                key: port
          - name: EventBus__Username
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key: username
          - name: EventBus__Password
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: vacationservice-service
spec:
  type: NodePort
  selector:
    app: vacationservice
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 30000