apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacationservice-deployment
spec:
  selector:
    matchLabels:
      app: vacationservice
  template:
    metadata:
      labels:
        app: vacationservice
    spec:
      containers:
      - name: vacationservice
        image: jokk-itu/vacationservice:master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: vacationservice-service
spec:
  type: NodePort
  selector:
    app: vacationservice
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 30000
