apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketservice-deployment
spec:
  selector:
    matchLabels:
      app: ticketservice
  template:
    metadata:
      labels:
        app: ticketservice
    spec:
      containers:
      - name: ticketservice
        image: jokk-itu/ticketservice:master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: ticketservice-service
spec:
  type: NodePort
  selector:
    app: ticketservice
  ports:
  - port: 5005
    targetPort: internal
    nodePort: 30005
