global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
    
  - job_name: 'eventbus'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
    - targets: ['eventbus:15692']   

  - job_name: 'vacationservice'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['vacationservice:80']
    
  - job_name: 'flightservice'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['flightservice:80']
 
  - job_name: 'hotelservice'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['hotelservice:80']
    
  - job_name: 'carservice'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['carservice:80']
    
  - job_name: 'trackingservice'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['trackingservice:80']
