apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightservice-deployment
spec:
  selector:
    matchLabels:
      app: flightservice
  template:
    metadata:
      labels:
        app: flightservice
    spec:
      containers:
      - name: flightservice
        image: jokk-itu/flightservice:master
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: flightservice-service
spec:
  type: NodePort
  selector:
    app: flightservice
  ports:
  - port: 5001
    targetPort: internal
    nodePort: 30001

