apiVersion: apps/v1
kind: Deployment
metadata:
  name: carservice-deployment
spec:
  selector:
    matchLabels:
      app: carservice
  replicas: 1
  template:
    metadata:
      labels:
        app: carservice
    spec:
      containers:
        - name: carservice
          image: jokk/carservice:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: carservice-port
          livenessProbe:
            httpGet:
              path: /health/live
              port: carservice-port
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: carservice-port
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Logging__SeqUri
              valueFrom:
                configMapKeyRef:
                  name: logger-config
                  key: url
            - name: EventBus__Hostname
              valueFrom:
                secretKeyRef:
                  name: eventbus-default-user
                  key: host
            - name: EventBus__Port
              valueFrom:
                secretKeyRef:
                  name: eventbus-default-user
                  key: port
            - name: EventBus__Username
              valueFrom:
                secretKeyRef:
                  name: eventbus-default-user
                  key: username
            - name: EventBus__Password
              valueFrom:
                secretKeyRef:
                  name: eventbus-default-user
                  key: password
            - name: RavenSettings__Urls__0
              valueFrom:
                configMapKeyRef:
                  name: raven-config
                  key: url
---
apiVersion: v1
kind: Service
metadata:
  name: carservice-service
spec:
  selector:
    app: carservice
  ports:
    - port: 5003
      targetPort: carservice-port
