apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventbus-ingress
  labels:
    name: eventbus-ingress
spec:
  rules:
  - host: bookvacation.local
    http:
      paths:
      - pathType: Prefix
        path: "/eventbus"
        backend:
          service:
            name: eventbus-service
            port: 
              name: management