apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Influx
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    orgId: 1
  - name: Influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: false
    version: 2
    orgId: 1
    basicAuth: true
    isDefault: false
    secureJsonData:
      token: iXnNAnWD3YXqqs95Dy1x7l2J-bXxZvzS_cLNs8wGHLT7pTp8lxsipx3Tzv-ElDf3bD4NLwYBz822GnUtouUesQ==
    jsonData:
      version: Flux
      organization: bookvacation
      defaultBucket: bookVacation
      httpMode: POST
      tlsSkipVerify: true
