name: Build & Test

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - feature/**
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    env:
        DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup BuildNumber
      run: |
        BuildNumber="$(echo $GITHUB_RUN_NUMBER)$(echo $GITHUB_RUN_ATTEMP)"
        echo "BuildNumber=$BuildNumber" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Authenticate to Github Nuget Repository
      run: dotnet nuget add source --username jokk-itu --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jokk-itu/index.json"    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build