name: Build & Test

on:
  pull_request:
    branches:
      - master
      - feature/**
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    env:
        DOTNET_NOLOGO: true
        CONFIGURATION: Release

    services:
      neo4j:
        image: neo4j
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/test
      eventbus:
        image: masstransit/rabbitmq
        ports:
          - 5672:5672
        volumes:
          - ./EventBus/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
          - ./EventBus/enabled_plugins:/etc/rabbitmq/enabled_plugins      

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup BuildNumber
      run: |
        BuildNumber="$GITHUB_RUN_NUMBER$GITHUB_RUN_ATTEMPT"
        echo "BuildNumber=$BuildNumber" >> $GITHUB_ENV
    - name: Setup GithubToken
      run: |
        GithubToken=${{ secrets.GITHUB_TOKEN }}
        echo "GithubToken=$GithubToken" >> $GITHUB_ENV    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $CONFIGURATION --no-restore  
    - name: Test
      run: dotnet test --no-build