name: Build, Test, Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
      
  push_images:
  
    runs-on: ubuntu-latest
    
    env:
      CONFIGURATION: Release
      ENVIRONMENT: Production
    
    strategy:
      matrix:
        services: ['Api', 'BookFlightService', 'BookHotelService', 'RentCarService', 'BookVacationService']
        
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish Services
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME}}/${{ matrix.services }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ${{ matrix.services }}/Dockerfile
          context: .
          buildargs: CONFIGURATION, ENVIRONMENT
          tags: "latest"
