name: Push to Github

on:
  push:
    branches: [ master ]

env:
  CONFIGURATION: Release 

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects:  ['CarService.Contracts', 'FlightService.Contracts', 'HotelService.Contracts', 'VacationService.Contracts', 'EventDispatcher']
    steps:
    - name: Checkout
      uses: actions/checkout/@v2
    - name: Setup BuildNumber
      run: |
        BuildNumber="$(echo GITHUB_RUN_NUMBER)$(echo GITHUB_RUN_ATTEMPT)"
        echo "BuildNumber=$BuildNumber" >> $GITHUB_ENV
    - name: Setup GithubToken
      run: |
        GithubToken=${{ secrets.GITHUB_TOKEN }}
        echo "GithubToken=$GithubToken" >> $GITHUB_ENV    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c $CONFIGURATION --no-restore
    - name: Push package to Github Nuget Repository
      run: |
        package=$(ls ${{ matrix.projects }}/bin/$CONFIGURATION/*nupkg)
        dotnet nuget push "$package" --source "github" --skip-duplicate